# Generated by Django 3.0.4 on 2020-03-27 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TubeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(default='Tube', max_length=20)),
                ('departTime', models.DateTimeField(auto_now_add=True)),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.FloatField()),
                ('direction', models.TextField()),
                ('departLon', models.FloatField()),
                ('departLat', models.FloatField()),
                ('arrivalLon', models.FloatField()),
                ('arrivalLat', models.FloatField()),
                ('carbonPrint', models.FloatField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TubeRoute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriveRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(default='Drive', max_length=20)),
                ('departTime', models.DateTimeField(auto_now_add=True)),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.FloatField()),
                ('direction', models.TextField()),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DriveRoute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CycleRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(default='Cycle', max_length=20)),
                ('departTime', models.DateTimeField(auto_now_add=True)),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.FloatField()),
                ('direction', models.TextField()),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CycleRoute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(default='Bus', max_length=20)),
                ('departTime', models.DateTimeField(auto_now_add=True)),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.FloatField()),
                ('direction', models.TextField()),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BusRoute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
