# Generated by Django 3.0.4 on 2020-03-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(max_length=20)),
                ('departTime', models.DateTimeField()),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.IntegerField()),
                ('direction', models.TextField(max_length=500)),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CycleRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(max_length=20)),
                ('departTime', models.DateTimeField()),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.IntegerField()),
                ('direction', models.TextField(max_length=500)),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(max_length=20)),
                ('departTime', models.DateTimeField()),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.IntegerField()),
                ('direction', models.TextField(max_length=500)),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TubeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('arrive', models.CharField(max_length=50)),
                ('travelBy', models.CharField(max_length=20)),
                ('departTime', models.DateTimeField()),
                ('arriveTime', models.DateTimeField()),
                ('duation', models.IntegerField()),
                ('direction', models.TextField(max_length=500)),
                ('departLon', models.IntegerField()),
                ('departLat', models.IntegerField()),
                ('arrivalLon', models.IntegerField()),
                ('arrivalLat', models.IntegerField()),
                ('carbonPrint', models.FloatField()),
            ],
        ),
    ]
