# Generated by Django 3.0.4 on 2020-03-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelby',
            old_name='travelBy',
            new_name='type',
        ),
    ]
