# Generated by Django 3.0.4 on 2020-03-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroute',
            old_name='owner',
            new_name='traveler',
        ),
        migrations.RenameField(
            model_name='cycleroute',
            old_name='owner',
            new_name='traveler',
        ),
        migrations.RenameField(
            model_name='driveroute',
            old_name='owner',
            new_name='traveler',
        ),
        migrations.RenameField(
            model_name='tuberoute',
            old_name='owner',
            new_name='traveler',
        ),
    ]
