# Generated by Django 3.0.4 on 2020-03-31 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuberoute',
            name='travelBy',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tubeRoutes', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubeRoutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
