# Generated by Django 3.0.4 on 2020-03-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelby',
            old_name='TravelBy',
            new_name='travelBy',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='travelBy',
        ),
        migrations.AddField(
            model_name='busroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='BusRoute', to='routes.TravelBy'),
        ),
        migrations.RemoveField(
            model_name='cycleroute',
            name='travelBy',
        ),
        migrations.AddField(
            model_name='cycleroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='CycleRoute', to='routes.TravelBy'),
        ),
        migrations.RemoveField(
            model_name='driveroute',
            name='travelBy',
        ),
        migrations.AddField(
            model_name='driveroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='DriveRoute', to='routes.TravelBy'),
        ),
        migrations.RemoveField(
            model_name='tuberoute',
            name='travelBy',
        ),
        migrations.AddField(
            model_name='tuberoute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='TubeRoute', to='routes.TravelBy'),
        ),
    ]
