# Generated by Django 3.0.4 on 2020-03-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0002_auto_20200323_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BusRoute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cycleroute',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CycleRoute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveroute',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DriveRoute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuberoute',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TubeRoute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='travelBy',
            field=models.CharField(default='Bus', max_length=20),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='departTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='travelBy',
            field=models.CharField(default='Cycle', max_length=20),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='departTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='travelBy',
            field=models.CharField(default='Drive', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='departTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='travelBy',
            field=models.CharField(default='Tube', max_length=20),
        ),
    ]
