# Generated by Django 3.0.4 on 2020-03-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0002_auto_20200329_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='busRoutes', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='busRoutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cycleRoutes', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cycleRoutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driveRoutes', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driveRoutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tubeRoutes', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tubeRoutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
