# Generated by Django 3.0.4 on 2020-03-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20200329_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BusRoute', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='cycleroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CycleRoute', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='driveroute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DriveRoute', to='routes.TravelBy'),
        ),
        migrations.AlterField(
            model_name='tuberoute',
            name='travelBy',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TubeRoute', to='routes.TravelBy'),
        ),
    ]
